NAME	= phonebook
SRC		= Contact.cpp main.cpp Phonebook.cpp
CC		= c++
FLAGS	= -Wall -Wextra -Werror

all : $(NAME)
$(NAME) :
	$(CC) -o $(NAME) $(FLAGS) $(SRC)
clean :
fclean : clean
	rm -rf $(NAME)
re : fclean all