NAME	= phonebook
SRC		= contact.class.cpp main.cpp phonebook.class.cpp
CC		= g++
FLAGS	= -Wall -Wextra -Werror

all : $(NAME)
$(NAME) :
	$(CC) -o $(NAME) $(FLAGS) $(SRC)
clean :
fclean : clean
	rm -rf $(NAME)
re : fclean all